config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'about', to: 'static_pages#about'
  get 'likes/index'
  get 'friendships/new'
  get 'friendships/create'
  get 'friendships/destroy'
  get 'comments/new'
  get 'comments/create'
  root to: 'posts#index'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users,:skip => [:registrations], controllers: { omniauth_callbacks: 'auth/callbacks'}
  
  devise_scope :user do
    put    '/account',  to: 'devise/registrations#update'
  delete '/account',  to: 'devise/registrations#destroy'
  post   '/account',  to: 'devise/registrations#create'
  get    '/register', to: 'devise/registrations#new',    as: :new_user_registration
  get    '/account/:id',  to: 'devise/registrations#edit',   as: :edit_user_registration
  patch  '/account',  to: 'devise/registrations#update', as: :user_registration
  get    '/account/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration# passwords




    #get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
    #post "user/sign_up", to: "users/registrations#create", as: :user_registration
    #get 'user/edit/:id' ,to: 'users/registrations#edit', as: :edit_user_registration
    #put 'user/update', to: 'users/registrations#update', as: :user_registrations
    
  end

  resources :users, only: [:index,:show,:edit,:update]

  resources :posts do
  	resources :comments
    resources :likes, only: [:index,:create,:destroy]
  end

  resources :comments do
  	resources :comments
  end

  resources :friendships
  resources :requests , only: [:index,:new,:create,:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  require 'open-uri'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :friends, foreign_key: 'friend_id', class_name: 'Friendship' , dependent: :destroy

  has_many :friend_requests_sent_relationship, foreign_key: 'sender_id' , class_name: 'Request'
  has_many :friend_requests_sent, through: :friend_requests_sent_relationship, source: :accepter

  has_many :friend_requests_received_relationship, foreign_key: 'accepter_id', class_name: 'Request'
  has_many :friend_requests_received, through: :friend_requests_received_relationship, source: :sender


  has_many :friends_relationship, foreign_key: 'friend_id' , class_name: 'Friendship' , dependent: :destroy
  has_many :friends, through: :friends_relationship, source: :user

  has_many :posts
  has_many :likes
  has_many :comments, foreign_key: 'user_id', class_name: 'Comment'

  has_one_attached :image

  after_commit :add_default_cover, on: [:create, :update]
  after_create :send_welcome_mail

  validates :name,presence: true

  def send_welcome_mail
    UserMailer.welcome_email(self).deliver
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      if user.image.attached?
      else
        # open the link
        downloaded_image = open(auth.info.image)

        # upload via ActiveStorage
        # be careful here! the type may be png or other type!
        user.image.attach(io: downloaded_image, filename: 'image.jpg', content_type: downloaded_image.content_type)
      end
    end
  end

  
  
  private
    

    def add_default_cover
      unless self.image.attached?
        self.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "default-picture.jpg")), filename: 'default-picture.jpg' , content_type: "image/jpg")
      end
    end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   #def update
     #super
    
   #end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_up_path_for(resource)
      "/posts"
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  

  def index
  	@users = User.all.where.not(id: current_user.friends.pluck(:id)).
    includes(image_attachment: [:blob]).paginate(:page => params[:page], :per_page => 32)
  end

  def show
  	@friendship = Friendship.new
  	@user = User.find_by(id: params[:id])
    @posts = @user.posts.includes(comments: [:user])
  
  end

  def destroy
  end

  def edit
  	@user = User.find_by(id: params[:id])
  end

  def update
  	@user = User.find_by(id: params[:id])
  	if params[:image].present? && @user.update_attributes(image: params[:image])
  		redirect_to user_path(@user)
  	else
  		flash.now[:danger] = "Please attach an image to proceed"
  		render 'show'
  	end
  end

  def user_params
  	params.require(:user).permit(:id,:name,:email,:password,:password_confirmation,:image)
  end


end

app/helpers/users_helper.rb
module UsersHelper
  
  def show_all_posts_of_friends
  	friends = current_user.friends
  	friends << current_user if display_posts_of_current_user
	friends.includes(posts: [{comments: :user},{image_attachment: :blob}],image_attachment: [:blob]).order(created_at: :ASC)
  end
end

app/views/users/_accept_ignore.html.erb
<%= button_to "Accept",
                    friendships_path, 
                    :params => { :user_id => user.id },
                    method: :post, remote: true,
                    class: 'btn btn-primary btn-sm accept' %>
<%= form_for( current_user.friend_requests_received_relationship.find_by(sender_id: user.id), method: :delete ,remote: true) do |f| %>
    <%= f.hidden_field :id, value: user.id %>
    <%= f.submit "Ignore", class: 'btn btn-primary ignore-button' %>
  <% end %>

app/views/users/_add_friend.html.erb
  <%= form_for( current_user.friend_requests_sent_relationship.build, remote: true) do |f| %>
    <%= f.hidden_field :accepter_id, value: user.id %>
    <%= f.submit "Add Friend", class: 'btn btn-primary btn-sm add-button' %>
  <% end %>

app/views/users/_add_friend_requested_from.html.erb
<div id='add_friend_requested_from<%=user.id%>'>
<% if  current_user.friend_requests_sent_relationship.find_by(accepter_id: @user.id).present? %>
  <%= render partial: 'users/requested'  %>
<% else %>
  <%= render partial: 'users/add_friend' %>
<% end %>
</div>

app/views/users/_image_thumbnail.html.erb
<%= image_tag(url_for(user.image.variant(resize: "50x50"))) if user.image.attached?%>

app/views/users/_remove_friend.html.erb
  <div class="btn btn-static disabled">Friends</div></br>
  <%= form_for(current_user.friends_relationship.find_by(user_id: user.id), controller: 'Friendships', html: {method: :delete}, remote: true) do |f|%>
  <%= f.hidden_field :user_id, value: user.id %>
    <%= f.submit "Remove friend", class: 'btn' %>
  <% end %>

app/views/users/_remove_friend_add_friend_form.html.erb
 <div id='remove_friend_add_friend_form'>
 <% if current_user.friends_relationship.find_by(user_id: user.id).present? %>
  <%= render partial: 'users/remove_friend', locals:{user: user} %>
<% else %>
  <%= render partial: 'users/add_friend',locals:{user: user} %>
<% end %>
</div>

app/views/users/_requested.html.erb
  <div class="btn btn-static disabled">Requested</div>
  <%= form_for( current_user.friend_requests_sent_relationship.find_by(accepter_id: user.id), method: :delete ,remote: true) do |f| %>
    <%= f.hidden_field :id, value: user.id %>
    <%= f.submit "Cancel Request", class: 'btn btn-primary add-button' %>
  <% end %>

app/views/users/_user_form.html.erb
<div id="user_form<%=user.id%>">
	  <% if current_user.friends_relationship.find_by(user_id: user.id).blank? && user.friend_requests_sent_relationship.find_by(accepter_id: current_user.id).blank? && user.friend_requests_received_relationship.find_by(sender_id: current_user.id).blank? %>
        <div class='add_friend<%=user.id%>'>
  		  <%= render partial: 'users/add_friend',locals: {user:  user} %><br>
        </div>
  	  <% end %>
      <% if  current_user.friend_requests_sent_relationship.find_by(accepter_id: user.id).present? && current_user.friends_relationship.find_by(user_id: user.id).blank? %>
        <div class='requested<%=user.id%>'>
        <%= render partial: 'users/requested' ,locals: {user: user} %>
        </div>
      <% end %>
      <% if current_user.friend_requests_received_relationship.find_by(sender_id: user.id).present? && current_user.friends_relationship.find_by(user_id: user.id).blank? %>
        <%= render partial: 'users/accept_ignore', locals: {user: user} %>
      <% end %>
  	
       <% if current_user.friends_relationship.find_by(user_id: user.id).present? %>
  		  <%= render partial: 'users/remove_friend_add_friend_form',locals: {user: user} %>
  	    <% end %>
  </div>

app/views/users/index.html.erb
<div class= 'container-users'>
  <% @users.each do |user| %>
    <% if user == current_user %>
    <% else %>
  	<div class= 'user-show-thumb'>
      <%= image_tag(url_for(user.image.variant(resize: "50x50"))) if user.image.attached?%>
      <%= user.name %>
      <%= render partial: 'users/user_form', locals:{user: user} %>
    <% end %>
    </div>
  <% end %>
</div>
<div class='pagination'>
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/users/show.html.erb
<div class="show-image">
<%= image_tag(url_for(@user.image.variant(resize: "200x200"))) if @user.image.attached?%>
</div>


<% if @user == current_user %>
  <div class='field'>
    <%= form_with url: user_url(@user),method: :patch,local: true do |f| %>
      <%= f.label :image %>
      <%= f.file_field :image,class: 'btn-default btn-file' %>
      <%= f.submit 'Attach image',class: 'btn-default btn-file'%> 
  </div>
    <% end %>
<% else %>
  <%= render partial: 'users/user_form', locals:{user: @user} %>
<% end %>

  <% @posts.each do |post| %>
  <div class="container-post" >
    <%= render partial: 'shared/post', locals: {post: post,user: @user} %>
  
    <%= render partial: 'posts/like_form',locals: {post: post} %>             
  
    <%= render partial: 'posts/form_comment', locals: {post: post} %>
    <p>Comment:</p>
    <%= render partial: 'posts/show_comment', locals: {comments: post.comments} %>
  </div>
  <% end %>