config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'about', to: 'static_pages#about'
  get 'likes/index'
  get 'friendships/new'
  get 'friendships/create'
  get 'friendships/destroy'
  get 'comments/new'
  get 'comments/create'
  root to: 'posts#index'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users,:skip => [:registrations], controllers: { omniauth_callbacks: 'auth/callbacks'}
  
  devise_scope :user do
    put    '/account',  to: 'devise/registrations#update'
  delete '/account',  to: 'devise/registrations#destroy'
  post   '/account',  to: 'devise/registrations#create'
  get    '/register', to: 'devise/registrations#new',    as: :new_user_registration
  get    '/account/:id',  to: 'devise/registrations#edit',   as: :edit_user_registration
  patch  '/account',  to: 'devise/registrations#update', as: :user_registration
  get    '/account/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration# passwords




    #get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
    #post "user/sign_up", to: "users/registrations#create", as: :user_registration
    #get 'user/edit/:id' ,to: 'users/registrations#edit', as: :edit_user_registration
    #put 'user/update', to: 'users/registrations#update', as: :user_registrations
    
  end

  resources :users, only: [:index,:show,:edit,:update]

  resources :posts do
  	resources :comments
    resources :likes, only: [:index,:create,:destroy]
  end

  resources :comments do
  	resources :comments
  end

  resources :friendships
  resources :requests , only: [:index,:new,:create,:destroy]
end

app/views/shared/_post.html.erb
<div id="activity-<%=post.id%>" class="activity container-post">
  <div class="activity-like">
    <div class="info">
      <div class="show-image">
		<%= image_tag(url_for(user.image.variant(resize: "50x50"))) if user.image.attached?%>
		<h4 class="name">Posted by: <%= link_to user.name, user_path(user.id) %></h4>
	  </div>   
    </div>
    <div class="content">
    <h4><small><%= post.body %> </small></h4>
    <h4><small><%= image_tag(url_for(post.image.variant(resize: "150x150"))) if post.image.attached?%></small></h4>
    <h4><small><i class="fa fa-calendar"></i> <%= post.created_at %></small></h4>
    </div>
  </div>
</div>

app/views/shared/_show_comment.html.erb
<div class='post-comments'>
<% comments.each do |comm| %></br>
  <% if comm.valid? %>
  <p><h5>Comment by: <%= link_to comm.user.name, user_path(comm.user.id) %></h5></br>
  <%= comm.body %>
  </p>
  <% else %>
  <% end %>
  <% #render partial: 'posts/sub_comments', locals:{comm: comm} %>
<% end %></br>
</div>

app/views/shared/_sub_comments.html.erb
<% comm.comments.each do |sub_comm| %><br>
    <p>Sub comment:</p>
    <%= sub_comm.user.name %></br>
    <%= sub_comm.body %></br>
    <%= link_to 'Reply', comment_comments_path(comm), method: :post %>
  <% end %>