config/routes.rb
Rails.application.routes.draw do
  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'about', to: 'static_pages#about'
  get 'likes/index'
  get 'friendships/new'
  get 'friendships/create'
  get 'friendships/destroy'
  get 'comments/new'
  get 'comments/create'
  root to: 'posts#index'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users,:skip => [:registrations], controllers: { omniauth_callbacks: 'auth/callbacks'}
  
  devise_scope :user do
    put    '/account',  to: 'devise/registrations#update'
  delete '/account',  to: 'devise/registrations#destroy'
  post   '/account',  to: 'devise/registrations#create'
  get    '/register', to: 'devise/registrations#new',    as: :new_user_registration
  get    '/account/:id',  to: 'devise/registrations#edit',   as: :edit_user_registration
  patch  '/account',  to: 'devise/registrations#update', as: :user_registration
  get    '/account/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration# passwords




    #get "user/sign_up", to: "users/registrations#new", as: :new_user_registration
    #post "user/sign_up", to: "users/registrations#create", as: :user_registration
    #get 'user/edit/:id' ,to: 'users/registrations#edit', as: :edit_user_registration
    #put 'user/update', to: 'users/registrations#update', as: :user_registrations
    
  end

  resources :users, only: [:index,:show,:edit,:update]

  resources :posts do
  	resources :comments
    resources :likes, only: [:index,:create,:destroy]
  end

  resources :comments do
  	resources :comments
  end

  resources :friendships
  resources :requests , only: [:index,:new,:create,:destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h4 style="text-align: center"><small>Created by Agon Idrizi</small>
        <%= link_to raw('<i class="fab fa-github"></i>'), "https://github.com/AgonIdrizi" %>
      </h4>
    </div>
  </div>
</footer>

app/views/layouts/_friend_request.html.erb
<li class="nav-item active dropdown">
    <a href="#" class="nav-link dropdown-toggle" 
                id="dropdownMenuButton" 
                data-toggle="dropdown" 
                aria-haspopup="true" 
                aria-expanded="true">
      <%= icon('fas', 'envelope')  %> Friend Requests
    </a>
    <div class="dropdown-menu-friend-request  dropdown-menu" aria-labelledby="dropdownMenuButton">
      <% if current_user.friend_requests_received.blank? %>
        <div class="dropdown-item">
          <h6 class="center"> You currently have no requests </h5>
        </div>
      <% else %>
        <% current_user.friend_requests_received.limit(10).each do |sender| %>
          <div class="dropdown-item-friend-request dropdown-item">
            
              
            
            <div class="request-dropdown-button-wrapper">
              <div class="request-dropdown-ignore dropdown-btn">
                 <% if current_user.friend_requests_received_relationship.find_by(sender_id: sender.id).present? && current_user.friends_relationship.find_by(user_id: sender.id).blank? %>
                    <div class="show-image">
                      <%= image_tag(url_for(sender.image.variant(resize: "50x50"))) if sender.image.attached?%>
                      <%= link_to sender.name , user_path(sender) %>
                    </div>
                    
                    <div class="accept-ignore">
                    <%= button_to "Accept",
                                          friendships_path, 
                                          :params => { :user_id => sender.id },
                                          method: :post, 
                                          class: 'btn btn-primary btn-sm accept' %>
                    <%= form_for( current_user.friend_requests_received_relationship.find_by(sender_id: sender.id), method: :delete ) do |f| %>
                        <%= f.hidden_field :id, value: sender.id %>
                        <%= f.submit "Ignore", class: 'btn btn-primary btn-sm ignore-button' %>
                  <% end %>
                  </div>
                  <div class="dropdown-divider-special dropdown-divider"></div>
                  <div class="showall">
                    <%= link_to 'Show All', requests_path, class: "showall-text" %>
                  </div>
                <% end %>
               </div>                
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
</li>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to 'Socialize', root_path,class: 'navbar-brand'%>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'About', about_path %></li>
    </ul>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li class="active"><%= link_to 'Home',root_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to 'Users', users_path%></li>
        <%= render 'layouts/friend_request' %>
        <%= render 'layouts/profile_dropdown' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Sign Out' , destroy_user_session_path,
                                  method: :delete, 
                                  id: 'logout-button' %></li>
      <% else %>
        <li><%= link_to 'Sign Up',new_user_registration_path%></li>
        <li><%= link_to 'Login', user_session_path%></li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_profile_dropdown.html.erb
<li class="nav-item active dropdown mr-sm-2">
  <a  class="nav-link dropdown-toggle" 
      href="#" id="navbarDropdown" 
      role="button" 
      data-toggle="dropdown" 
      aria-haspopup="true" 
      aria-expanded="false">
    Account
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <%= link_to icon('fas', 'user-alt') + " Profile", 
                current_user, 
                class: "dropdown-item" %></br>
    <%= link_to icon('fas', 'user-friends') + " Friends", 
                friendships_path, 
                class: "dropdown-item" %></br>
    <%= link_to icon('fas', 'cog') + " Settings", 
                edit_user_registration_path(current_user),
                class: "dropdown-item" %></br>
    <div class="dropdown-divider"></div>
     <%= link_to icon('fas', 'sign-out-alt') + " Log out", 
          destroy_user_session_path , 
          method: :delete, 
          id: 'logout-button',
          class: "dropdown-item" %></br>
  </div>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialize</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    
    <div class="container">
      
      <%= yield %>
      
      <% debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/errors.html.erb
<h1>Errosss</h1>